# Generated by Django 5.1.6 on 2025-04-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0003_remove_event_organizer_alter_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
